### ISSUE TITLE
Keybind Manager doesn't render keys

### ISSUE THREAD

**Issue by MarkGG8181** [Sigma-Skidder-Team/SigmaRebase#6]
Also prints this error in the console: ``[20:26:04] [main/INFO]: [STDOUT]: totalcross.json.JSONException: Invalid (Unknown file): JSONObject["children"] not found. - key: children``
![image](https://github.com/user-attachments/assets/2d9fb004-b2f7-451e-b0f4-3a3d3edc7069)

**Comment by DataM0del** [comment]
a48c877163e221075cd9102ceba9debb7ab28787 causes this, the last good working commit is 7bd0a43e6706da162b03141853faa0755d8b2211
